<?php
include ('include/header.php');
?>
<title>Privacy Notice</title></title>
<style>
    .img-txt h4{
        color: white;
        font-size: 1.2em;
    }
    #banner::before{
        background: rgba(0, 0, 0, 0) !important;
    }

</style>

<!-- ========= banner section start ======= -->
<section id="banner" style="background-image: url('img/Services.jpg')">
    <div class="bnr-cont">
        <div class="container text-center">
             <h1> Privacy Notice</h1>
        </div>
    </div>
</section>
<!-- ========= end of banner section ======= -->

<!-- ====== intro section start  ======= -->
<section id="intro">
    <div class="container">
        <div class="row py-lg-5 ">
            <div class="col-md-12 intro-txt">
                <p class="p mb-4">
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:24px;font-family:"Times New Roman",serif;'>Privacy Notice for Arthur Lawrence&nbsp;</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>This privacy notice describes why and how we collect, use, and share personal information collected from individuals themselves or from other third parties. It provides information about individuals&rsquo; rights with respect to their personal information. We may use personal information provided to us for any of the purposes described in the relevant section of this privacy statement or as otherwise stated at the point of collection.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Our goal is to process personal information as necessary for our legitimate business purposes in a transparent manner. If you have any questions regarding our privacy practices, please contact us as set forth in the Contact Us section below.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><em><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>This Privacy Notice was updated on July 16<sup>th</sup>, 2020.</b></span></em></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><em><span style='font-size:16px;font-family:"Times New Roman",serif;'>We may update our privacy practices periodically. This Privacy Notice will be updated whenever there are changes to how we handle your Personal Data and how we accommodate applicable laws.</span></em></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Definitions:</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&ldquo;<strong>Personal Data</strong>&rdquo; refers to information that may be reasonably associated with, linked to, or used to individually identify an individual or allow an individual to be personally identified or contacted. For example, Personal Information may include information such as your name, email address, telephone number, address, or credit card number, either alone or in combination with other information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>&ldquo;<strong>Sensitive Personal Data</strong>&rdquo; refers to Personal Data regarding sensitive matters such as &nbsp;physical or mental health, genetic data, biometric data, sexual practices or sexual orientation, criminal records, race or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, or other sensitive matters.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Our purpose for collecting and using your Personal Data</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence collects and uses your Personal Data when required for specific purposes.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>The purposes are:</b></span></p>
<ul style="margin-bottom:0in;" type="disc">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To provide professional services to our customers</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To recruit and evaluate candidates for employment or contract positions with our company</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To manage and provide benefits to our employees and contractors</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To comply with state and federal regulatory requirements</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To maintain contracts and agreements with our customers, prospective customers and vendors</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To monitor and secure our IT infrastructure and that of our customers</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To identify companies and persons at those companies who may benefit from our services and to market our services to them</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To perform data analytics to support the above</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Personal Data that we collect</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence collects your Personal Data explicitly when you voluntarily provide your data with your consent (e.g., when you subscribe to any of our services, request information from us, apply for a job, accept an offer for employment or contracted services, or enroll in benefits).&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We also collect certain categories of your Personal Data implicitly (using automatic tracking technologies) when you visit our website (e.g., Cookies, IP Address, Geolocation etc.). &nbsp;The information we collect using these technologies includes IP address, browser type and language, access time, and referring website.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We collect information via cookies when you visit our web sites. &nbsp;Cookies are small text files placed on your hard drive that assist us in providing a more customized website experience. For example, a cookie can be used to store registration information in an area of the website so that a user does not need to re-enter it on subsequent visits to that area.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We may also obtain Information about you from third parties who have a legal basis to provide us with your information. We may use information about you which we receive from a third party in accordance with the terms we establish with that third party.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Sharing your Personal Data with third parties</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We may share your Personal Data with third parties who provide data processing services on our behalf. Before doing so we will ensure that the third party has committed to only use your Personal Data for the purposes we have contracted with them to provide and to protect your data and not use or disclose your data except as permitted by applicable laws and regulations.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Retaining and deleting Personal Data</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence retains your data for as long as required by relevant laws and regulations, and our business requirements relevant to the reason you provided your data to us. Arthur Lawrence deletes, and purges data periodically based upon its Data Retention and Removal policy.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Collecting/Sharing Sensitive Personal Data</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence only collects Sensitive Personal Data with the consent of the individual. Furthermore, Sensitive Personal Data is only collected if it is required by law or regulation or when necessary to provide the individual with a benefit that the individual has requested. Arthur Lawrence takes reasonable and appropriate measures to restrict access to any Sensitive Personal Data collected to only those employees, contractors or vendors whose jobs or responsibilities require such access. &nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>International transfers of your Personal Data</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence is an international organization with presence in USA and other locations, and we may store or process information, including personal data, within our corporate infrastructure in these locations.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We abide by all contractual and applicable legal restrictions on the international transfer of data.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Your rights per GDPR</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>If you are an individual located in the European Economic Area, in certain circumstances under applicable law (specifically in connection with certain services that we provide), you may have the right to access or obtain a copy of your Personal Data, to rectify your Personal Data, to have your Personal Data deleted, to restrict the processing of your Personal Data, to object to the processing of your Personal Data, to data portability, and to withdraw your consent for processing (where processing is based on your consent). Please note that if you withdraw your consent, we may not be able to provide you the services for which it was necessary to process your information based on your consent.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>If you want to practice any of your rights related to GDPR, please reach out to Arthur Lawrence using the information in the Privacy Contacts section within this document.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>California Privacy Rights </b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>If you are a California resident, please visit <a href="/cal-privacy-notice.php"><b>California Privacy Notice</b></a> for additional information about our processing of personal information and your California privacy rights.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Children</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence&rsquo;s services are not directed to children under the age of 13. &nbsp;Arthur Lawrence does not knowingly collect Personal Data from persons under the age of 13. &nbsp;If you are a parent of a child under 13, and you believe that your child has provided us with information about himself or herself, please contact us at <b><a href="mailto:privacy@arthurlawrence.net">privacy@arthurlawrence.net</a></b>. Note: Personal Data about children of employees may be collected from the parent when required to provide benefits to employee and their family.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>About cookies</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Our website uses cookies to personalize content and to provide you with an improved user experience. By continuing to browse this site you consent to the use of cookies. Please visit our cookie policy for further details.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'> <b>Privacy Contact</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'></span></strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>11233 Shadow Creek Parkway</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Suite 299, Pearland, TX 77584</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Tel:+1 (713) 401 9034</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Email: <span style="color:blue;text-decoration:underline;"><a href="mailto:privacy@arthurLawrence.net">privacy@arthurlawrence.net</a></span></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>                </p>
               
            </div>
           
        </div>
    </div>
</section>


<?php
include ('include/footer.php');
?>

