<?php
include ('include/header.php');
?>

<title>California Privacy Rights</title>
<style>
    .img-txt h4{
        color: white;
        font-size: 1.2em;
    }
    #banner::before{
        background: rgba(0, 0, 0, 0) !important;
    }

</style>

<!-- ========= banner section start ======= -->
<section id="banner" style="background-image: url('img/Services.jpg')">
    <div class="bnr-cont">
        <div class="container text-center">
             <h1>California Privacy Notice</h1>
        </div>
    </div>
</section>
<!-- ========= end of banner section ======= -->

<!-- ====== intro section start  ======= -->
<section id="intro">
    <div class="container">
        <div class="row py-lg-5 ">
            <div class="col-md-12 intro-txt">
                <p class="p mb-4">
               <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:24px;font-family:"Times New Roman",serif;'>California PRIVACY NOTICE for Arthur Lawrence&nbsp;</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>This privacy statement for California residents supplements the information contained in our main Privacy Statement and applies solely to individuals who reside in the State of California. If you have any questions about the information provided in this privacy statement or our privacy practices, please contact us as set forth in the <strong>Privacy Contact</strong> section below.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Definitions:</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>&ldquo;Personal Data&rdquo;</span></strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;refers to information that may be reasonably associated with, linked to, or used to individually identify an individual or allow an individual to be personally identified or contacted. For example, Personal Information may include information such as your name, email address, telephone number, address, or credit card number, either alone or in combination with other information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>&ldquo;Sensitive Personal Data&rdquo;</span></strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;refers to Personal Data regarding sensitive matters such as &nbsp;physical or mental health, genetic data, biometric data, sexual practices or sexual orientation, criminal records, race or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, or other sensitive matters.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Our purpose to use your Personal Data:</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence uses your Personal Data when required for specific purposes.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>The purposes are:</span></p>
<ul style="margin-bottom:0in;" type="disc">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To provide professional services to our customers</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To recruit and evaluate candidates for employment or contract positions with our company</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To manage and provide benefits to our employees and contractors</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To comply with state and federal regulatory requirements</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To maintain contracts and agreements with our customers, prospective customers and vendors</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To monitor and secure our IT infrastructure and that of our customers</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To identify companies and persons at those companies who may benefit from our services and to market our services to them</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- To perform data analytics to support the above</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Personal Data that we collect</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence collects your Personal Data explicitly when you voluntarily provide your data with your consent (e.g., when you subscribe to any of our services, request information from us, apply for a job, accept an offer for employment or contracted services, or enroll in benefits).&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We also collect certain categories of your Personal Data implicitly (using automatic tracking technologies) when you visit our website (e.g., Cookies, IP Address, Geolocation etc.). &nbsp;The information we collect using these technologies includes IP address, browser type and language, access time, and referring website.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We collect information via cookies when you visit our web sites. &nbsp;Cookies are small text files placed on your hard drive that assist us in providing a more customized website experience. For example, a cookie can be used to store registration information in an area of the website so that a user does not need to re-enter it on subsequent visits to that area.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We may also obtain Information about you from third parties who have a legal basis to provide us with your information. We may use information about you which we receive from a third party in accordance with the terms we establish with that third party.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Sharing your Personal Data with third parties</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>We may share your Personal Data with third parties who provide data processing services on our behalf. Before doing so we will ensure that the third party has committed to only use your Personal Data for the purposes we have contracted with them to provide and will protect your data and not use or disclose your data except as permitted by applicable laws and regulations.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Retaining and deleting Personal Data</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence retains your data for as long as required by relevant laws and regulations and our business requirements relevant to the reason you provided your data to us. Arthur Lawrence deletes, and purges data periodically based upon its Data Retention and Removal policy.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Collecting/Sharing Sensitive Personal Data</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence only collects Sensitive Personal Data with the consent of the individual. Furthermore, Sensitive Personal Data is only collected if it is required by law or regulation or when necessary to provide the individual with a benefit that the individual has requested. Examples of Sensitive Personal Data include race or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, physical or mental health, genetic data, biometric data, sexual practices or sexual orientation, and criminal records. Arthur Lawrence ensures that access to any Sensitive Personal Data collected is restricted to only those employees, contractors or vendors whose jobs or responsibilities require such access.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>California Privacy Rights</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>This section describes the rights of California residents under California law and explains how to exercise those rights.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Request to Know:</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>If you are a California resident, under certain circumstances in accordance with applicable law, you have the right to request that we disclose to you specific details about your personal information that we have collected, used, disclosed and sold over the past 12 months and/or a copy of your personal information. These details include: (1) the categories of personal information we have collected about you; (2) the categories of sources from which the personal information is collected; (3) the business or commercial purpose for collecting or selling personal information; (4) the categories of third parties with whom we share personal information; (5) the specific pieces of personal information we have collected about you.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Once we receive your request, we will acknowledge it and either respond in accordance with law, ask for additional information to verify your identity, clarify the nature of your request, let you know if we need more time, let you know if we need to charge a fee (such as if requests are manifestly unfounded or excessive, in particular because of their repetitive character, taking into account the administrative costs of providing the information or communication or taking the action requested), or we will inform you if we cannot fulfill any part of your request due to an exception under the law. If we know that your request relates to information we process as a service provider to one of our corporate clients, we will forward your request to the relevant client and cooperate with that client as needed to address your request and/or inform you that your request should be submitted directly to the business on whose behalf we process the information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Request to Delete</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>If you are a California resident, under certain circumstances in accordance with applicable law, you have the right to request that we delete any of your personal information that we collected from you and retained, subject to certain exceptions. Once we receive and confirm your valid verifiable request, we will delete, de-identify or aggregate your personal information and direct our service providers to do so, or we will inform you if we cannot fulfill any part of your request due to an exception under the law. If your request relates to information we process as a service provider to one of our clients, we will inform you that your request should be submitted directly to the business on whose behalf we process the information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Submitting a request to Know or to Delete:</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>To exercise the rights described above, please submit a verifiable request to us by either:</span></p>
<ul style="margin-bottom:0in;" type="disc">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- Use the request link here, OR</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>- Contact us using the information in the <strong>Privacy Contacts</strong> section below</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Special notice for California Residents &ndash; Do Not Sell My Information</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>If you are a California resident, you have the right to direct a business not to sell your Personal Data. Please note that Arthur Lawrence has not sold within the last twelve (12) months and does not sell Personal Data. We do not sell the Personal Data of minors under 16 years of age or any other Personal Data.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Children</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Arthur Lawrence&rsquo;s services are not directed to children under the age of 13. Arthur Lawrence does not knowingly collect Personal Data from persons under the age of 13. &nbsp;If you are a parent of a child under 13, and you believe that your child has provided us with information about himself or herself, please contact us at <b><a href="mailto:privacy@arthurlawrence.net">privacy@arthurlawrence.net</a></b> Note: Personal Data about children of employees may be collected from the parent when required to provide benefits to employee and their family.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>About cookies</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Our website uses cookies to personalize content and to provide you with an improved user experience. By continuing to browse this site you consent to the use of cookies. Please visit our cookie policy for further details.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'><b>Privacy Contact</b></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;font-family:"Times New Roman",serif;'></span></strong><span style='font-size:16px;font-family:"Times New Roman",serif;'>11233 Shadow Creek Parkway</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Suite 313, Pearland, TX 77584</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Tel:+1 (713) 401 9034</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-size:16px;font-family:"Times New Roman",serif;'>Email: <span style="color:blue;text-decoration:underline;"><a href="mailto:privacy@arthurlawrence.net">privacy@arthurlawrence.net</a></span></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
                </p>
               
        </div>
    </div>
</section>
<!-- ====== //end of intro section ======= -->

<!-- ===== capability section start ===== -->


<?php
include ('include/footer.php');
?>

